In [1]:
import pandas as pd
from tableone import TableOne, load_dataset

In [2]:
train = pd.read_csv("~/project/n2c2/2022/Data/train.csv")
dev = pd.read_csv("~/project/n2c2/2022/Data/dev.csv")
test = pd.read_csv("/home/vs428/project/n2c2/2022/Data/n2c2_track3_test.csv")

In [3]:
data = pd.concat([train,dev, test])

In [4]:
data

,ROW ID,HADM ID,Assessment,Plan Subsection,Relation
0,701359,186454,"51 yr old F with a history of 3V CAD, confirme...",# CORONARIES: Patient with 3 vessel disease on...,Direct
1,701359,186454,"51 yr old F with a history of 3V CAD, confirme...",# Acute on Chronic systolic CHF: Patient with ...,Indirect
2,701359,186454,"51 yr old F with a history of 3V CAD, confirme...",# Social stressors: Recently lost mother to ca...,Neither
3,701359,186454,"51 yr old F with a history of 3V CAD, confirme...","# FEN: Replete lytes PRN, NPO for CABG today\n...",Not Relevant
4,554144,196435,"CHRONIC OBSTRUCTIVE PULMONARY DISEASE (COPD, B...",# Dyspnea: Differential in this patient would ...,Direct
...,...,...,...,...,...
662,560683,196558,"DEEP VENOUS THROMBOSIS (DVT), UPPER EXTREMITY\...",5) HTN: Cont lisinopril,Neither
663,560683,196558,"DEEP VENOUS THROMBOSIS (DVT), UPPER EXTREMITY\...",6) CRI: Last Cr 1.2: Hold naproxen given...,Neither
664,560683,196558,"DEEP VENOUS THROMBOSIS (DVT), UPPER EXTREMITY\...","7) Nausea: likely chemo SE, cont compazi...",Neither
665,560683,196558,"DEEP VENOUS THROMBOSIS (DVT), UPPER EXTREMITY\...","8) Hyperglycemia: trend, consider HISS",Neither
666,560683,196558,"DEEP VENOUS THROMBOSIS (DVT), UPPER EXTREMITY\...","9) FEN: repleted K, Mg\n [**Month/Year ...",Not Relevant

In [5]:
pts = pd.read_csv("/home/vs428/project/MIMIC/files/mimiciii/1.4/PATIENTS.csv")

In [6]:
pts

,ROW_ID,SUBJECT_ID,GENDER,DOB,DOD,DOD_HOSP,DOD_SSN,EXPIRE_FLAG
0,234,249,F,2075-03-13 00:00:00,NaN,NaN,NaN,0
1,235,250,F,2164-12-27 00:00:00,2188-11-22 00:00:00,2188-11-22 00:00:00,NaN,1
2,236,251,M,2090-03-15 00:00:00,NaN,NaN,NaN,0
3,237,252,M,2078-03-06 00:00:00,NaN,NaN,NaN,0
4,238,253,F,2089-11-26 00:00:00,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...
46515,31840,44089,M,2026-05-25 00:00:00,NaN,NaN,NaN,0
46516,31841,44115,F,2124-07-27 00:00:00,NaN,NaN,NaN,0
46517,31842,44123,F,2049-11-26 00:00:00,2135-01-12 00:00:00,2135-01-12 00:00:00,NaN,1
46518,31843,44126,F,2076-07-25 00:00:00,NaN,NaN,NaN,0
46519,31844,44128,M,2098-07-25 00:00:00,NaN,NaN,NaN,0

In [7]:
hadms = pd.read_csv("/home/vs428/project/MIMIC/files/mimiciii/1.4/ADMISSIONS.csv")

In [8]:
diags = pd.read_csv("/home/vs428/project/MIMIC/files/mimiciii/1.4/DIAGNOSES_ICD.csv")

In [9]:
icd_map = pd.read_csv("/home/vs428/project/MIMIC/files/mimiciii/1.4/D_ICD_DIAGNOSES.csv")

In [ ]:
notes = pd.read_csv("/home/vs428/project/MIMIC/files/mimiciii/1.4/NOTEEVENTS.csv")

In [ ]:
data[data['HADM ID'] == 192825]

In [ ]:
# notes[notes['HADM_ID'].isin(data['HADM ID'])]['HADM_ID'].value_counts()
x = notes[notes['HADM_ID'] == 192825]
# 49669

In [ ]:
print(x[x['TEXT'].str.contains("57 yo M with PMHx of alcoholic ESLD on transpl")].sort_values("CHARTTIME").iloc[-1]['TEXT'])

In [44]:
# set(icd_map['ICD9_CODE'].str.slice(0,3))

In [10]:
primary_diags = diags[diags['SEQ_NUM'] == 1]

In [48]:
primary_diags

        ROW_ID  SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
0         1297         109   172335      1.0     40301
14        1311         109   173633      1.0     40301
28        1488         112   174105      1.0     53100
33        1493         113   109976      1.0      1915
36        1496         114   178393      1.0     41401
...        ...         ...      ...      ...       ...
650989  639745       97488   152542      1.0       566
651000  639756       97488   161999      1.0     43411
651024  639780       97492   189314      1.0     34680
651032  639788       97497   168949      1.0      0529
651041  639797       97503   188195      1.0      7842

[58929 rows x 5 columns]

# Read S/O from n2c2 Project

In [10]:
import re

In [11]:
so_eval = pd.read_csv("/home/vs428/project/n2c2/2022/Task-1_Eval.csv", sep="|")
so_test = pd.read_csv("/home/vs428/project/n2c2/2022/Task-1_Test.csv", sep="|")
so_train = pd.read_csv("/home/vs428/project/n2c2/2022/Task-1_Train.csv", sep="|")

In [12]:
sodata = pd.concat([so_eval, so_test, so_train])

In [13]:
sodata.to_csv("/home/vs428/project/n2c2/2022/SO_sections.csv", index=False)

In [14]:
data['HADM ID'].isin(sodata['HADM_ID'].unique())

0      True
1      True
2      True
3      True
4      True
       ...
662    True
663    True
664    True
665    True
666    True
Name: HADM ID, Length: 5897, dtype: bool

In [15]:
sodata['BOUNDARY'] = sodata['LABEL'].str.slice(0,1)
sodata['SOAP_SECTION'] = sodata['LABEL'].str.slice(1,2)

In [16]:

_RE_COMBINE_WHITESPACE = re.compile(r"\s+")
# my_str = _RE_COMBINE_WHITESPACE.sub(" ", my_str).strip()
sodata['TEXT'] = sodata['TEXT'].str.replace(r"\s+", " ", regex=True)

In [30]:
sodata

,HADM_ID,TEXT,LABEL,DOCUINDEX,BOUNDARY,SOAP_SECTION
0,112508,NGT placed/TF started,BS,0,B,S
1,112508,Femoral line changed over wire by IR,IS,1,I,S
2,112508,"c diff x 2 negative, 3rd pending",IS,2,I,S
3,112508,d/c'ed gentamicin per ID,IS,3,I,S
4,112508,Sulfa (Sulfonamides),BS,4,B,S
...,...,...,...,...,...,...
106120,192715,20 Gauge - [**2177-10-24**] 07:14 PM,IP,199,I,P
106121,192715,Prophylaxis:,IP,200,I,P
106122,192715,DVT: SQ UF Heparin,IP,201,I,P
106123,192715,Stress ulcer: H2 blocker,IP,202,I,P
106124,192715,VAP:,IP,203,I,P

In [18]:
so_from_data = {}
# for idx, group in sodata.groupby("HADM_ID"):
#     so_from_data[idx] = {}
#     sorted_grp = group.sort_values(by="DOCUINDEX")
#     boundary, soap_sec = sorted_grp.iloc[0]['LABEL']
    
#     if boundary != "B":
#         raise Exception("HMM")
        
#     i = 1
#     out = {"S":[],"O":[],"A":[],"P":[]}
#     while i <= sorted_grp.shape[0]:
#         text_subset = []
#         text_subset.append(sorted_grp.iloc[i-1]['TEXT'])
#         while sorted_grp.iloc[i]['BOUNDARY'] != "B":
#             text_subset.append(sorted_grp.iloc[i]['TEXT'])
#             i += 1
#             print(i)
#         print(text_subset)

#         out[sorted_grp.iloc[i]['SOAP_SECTION']].append(text_subset)
#         i += 1
#     break

In [19]:
d = dict(tuple(sodata.groupby(sodata['BOUNDARY'].eq('B').cumsum())))

In [20]:
from collections import defaultdict

In [21]:
# d[i]['SOAP_SECTION'].unique()[0]

In [22]:
# def default_value():
#     return {"S":[],"O":[],"A":[],"P":[]}

# so_from_data = defaultdict(default_value)
# for i in range(1, max(d.keys())):
#     # sec_from_data = defaultdict(default_value)
#     # print(d[i])
#     # break
#     so_from_data[d[i]['HADM_ID'].unique()[0]][d[i]['SOAP_SECTION'].unique()[0]].append(d[i]['TEXT'].str.cat(sep=" "))

def default_value():
    return {"S":"","O":"","A":"","P":""}

so_from_data = defaultdict(default_value)
for i in range(1, max(d.keys())):
    # sec_from_data = defaultdict(default_value)
    # print(d[i])
    # break
    so_from_data[d[i]['HADM_ID'].unique()[0]][d[i]['SOAP_SECTION'].unique()[0]] += d[i]['TEXT'].str.cat(sep=" ")

In [23]:
len(data['HADM ID'].unique())

759

In [24]:
so_df = pd.DataFrame.from_records(so_from_data).T.reset_index()

In [25]:
so_df = so_df.rename({"index":"HADM_ID"}, axis=1)

In [31]:
so_df

,HADM_ID,S,O,A,P
0,100018,HPI: 55 y.o. Male w/ extensive history includ...,Current medications: Metoprolol Tartrate 37.5...,,
1,100215,- Received 2 units FFP prior to LP. Multiple ...,Last dose of Antibiotics: Ceftriaxone - [**21...,,
2,100326,MULTI LUMEN - START [**2159-8-12**] 01:36 PM ...,Last dose of Antibiotics: Metronidazole - [**...,,
3,100391,dyspnea STOOL CULTURE - At [**2138-12-8**] 03...,Last dose of Antibiotics: Infusions: Other I...,,
4,100456,4 Hour Events: - Fluid resuscitation overnigh...,Last dose of Antibiotics: Piperacillin/Tazoba...,,
...,...,...,...,...,...
760,199779,SepsisHPI: BLOOD CULTURED - At [**2198-8-2...,Last dose of Antibiotics: Piperacillin/Tazoba...,"Ascending cholangitis, sepsis.",SEPSIS -- Improved. Monitor VS. Continue suppo...
761,199781,-was intubated for acute psychosis - very com...,Last dose of Antibiotics: Infusions: Other I...,,
762,199789,"HPI: 65 yo M POD 1 from CABGx4 (LIMA-LAD, SVG...","*Last Name (un) 508**]: Atenolol 100', Lisinop...",CORONARY ARTERY BYPASS GRAFT (CABG) and Plan:...,"Neurologic: Neuro checks Q: 4 hr, Pain not wel..."
763,199790,- IP: not a candidate for Pleurex - cont on ...,Last dose of Antibiotics: Ciprofloxacin - [**...,74 yo F with metastatic endometrial cancer wit...,# Hypoxia/respiratory distress - In setting of...
764,199948,Chief Complaint INVASIVE VENTILATION - STOP [*...,Infusions: Other ICU medications: Fentanyl -...,74 F with no contributory PMH but a CXR with h...,"# Acute Hypoxic, Hypercarbic Respiratory Failu..."

In [27]:
data_with_so = data.merge(so_df[["HADM_ID", 'S', "O"]], left_on="HADM ID", right_on="HADM_ID", how='inner')

In [28]:
train_with_so = train.merge(so_df[["HADM_ID", 'S', "O"]], left_on="HADM ID", right_on="HADM_ID", how='inner')
dev_with_so = dev.merge(so_df[["HADM_ID", 'S', "O"]], left_on="HADM ID", right_on="HADM_ID", how='inner')
test_with_so = test.merge(so_df[["HADM_ID", 'S', "O"]], left_on="HADM ID", right_on="HADM_ID", how='inner')

In [37]:
train_with_so[["ROW ID", "HADM ID", 'S', 'O']]#.to_csv("~/project/n2c2/2022/Data/train_so.csv", index=False)
train_with_so['SO'] = train_with_so['S'] + "\n\n-----------------------------------\n\n" + train_with_so['O']

In [45]:
train_with_so.rename({"SO":"text"}, axis=1).to_csv("~/project/n2c2/2022/Data/train_so_annotations.csv", index=False)

In [46]:
# train = pd.read_csv("~/project/n2c2/2022/Data/train.csv")
# dev = pd.read_csv("~/project/n2c2/2022/Data/dev.csv")
# test = pd.read_csv("/home/vs428/project/n2c2/2022/Data/n2c2_track3_test.csv")

train_with_so.to_csv("~/project/n2c2/2022/Data/train_so.csv", index=False)
dev_with_so.to_csv("~/project/n2c2/2022/Data/dev_so.csv", index=False)
test_with_so.to_csv("/home/vs428/project/n2c2/2022/Data/n2c2_track3_test_so.csv", index=False)

In [47]:
sodata#[175]['LABEL']

,HADM_ID,TEXT,LABEL,DOCUINDEX,BOUNDARY,SOAP_SECTION
0,112508,NGT placed/TF started,BS,0,B,S
1,112508,Femoral line changed over wire by IR,IS,1,I,S
2,112508,"c diff x 2 negative, 3rd pending",IS,2,I,S
3,112508,d/c'ed gentamicin per ID,IS,3,I,S
4,112508,Sulfa (Sulfonamides),BS,4,B,S
...,...,...,...,...,...,...
106120,192715,20 Gauge - [**2177-10-24**] 07:14 PM,IP,199,I,P
106121,192715,Prophylaxis:,IP,200,I,P
106122,192715,DVT: SQ UF Heparin,IP,201,I,P
106123,192715,Stress ulcer: H2 blocker,IP,202,I,P
106124,192715,VAP:,IP,203,I,P